### ISSUE TITLE
添加 axios 后报错

### ISSUE THREAD

**Issue by xxyuze** [NewFuture/miniprogram-build#33]
```
[10:27:01] 8.npm: <axios> [×] Error
 Unexpected token (Note that you need rollup-plugin-json to import JSON files)

Error: Unexpected token (Note that you need rollup-plugin-json to import JSON files)
    at error (...\node_modules\rollup\dist\rollup.js:9373:30)
    at Module.error (...\node_modules\rollup\dist\rollup.js:13267:9)
    at tryParse (...\node_modules\rollup\dist\rollup.js:13183:16)
    at Module.setSource (...\node_modules\rollup\dist\rollup.js:13487:33)
    at Promise.resolve.catch.then.then.then (...\node_modules\rollup\dist\rollup.js:16248:20)
Error in plugin "gulp-better-rollup"
Message:
    Unexpected token (Note that you need rollup-plugin-json to import JSON files)
Details:
    code: PARSE_ERROR
    pos: 10
    loc: [object Object]
    frame: 1: {
2:   "name": "axios",
           ^
3:   "version": "0.18.1",
4:   "description": "Promise based HTTP client for the browser and node.js",

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NewFuture** [comment]
可能是 要 import JSON 文件的问题
可以加一下 对 json的支持

**Comment by NewFuture** [comment]
网络库也可以用这个miniprogram-network  https://github.com/NewFuture/miniprogram-network
和 axios提供类似的API, 更适合小程序

**Comment by xxyuze** [comment]
因为需要用到 nswag 自动生成的 客户端代码，所以只能用axios

**Comment by NewFuture** [comment]
https://github.com/NewFuture/miniprogram-build/blob/master/src/lib/rollup-plugins.js

https://github.com/NewFuture/miniprogram-build/blob/master/src/lib/rollup-plugins.js

这个里面加一个 rollup-plugin-json的 配置试试
没问题可以顺便提个PR

**Comment by NewFuture** [comment]
https://github.com/NewFuture/miniprogram-build/releases/tag/v6.4.3 支持 import json

**Comment by xxyuze** [comment]
谢谢你这么积极维护，这些天比较忙，已经请假不工作了。
很喜欢这个库，你的代码我想也得花些时间才能弄得懂。或许我能做的贡献是宣传一下，写点使用教程和经验分享。
